# バージョンの設定
FROM node:18-alpine

# ディレクトリを作成
WORKDIR /app

# package.json package-lock.jsonをコピー
COPY package.json package-lock.json ./

# node_modulesをインストール
RUN npm install

# ソースコードをコピー
COPY . .

# ビルド
RUN npm run build
